version: "3.9"
services:
  worker:
    build: .
    environment:
      SUDOERS: $SUDOERS # false
      API_ID: $API_ID  # true
      API_HASH: $API_HASH  # true
      LANGUAGE: $LANGUAGE # false
      CUSTOM_QUALITY: $CUSTOM_QUALITY  # false
      PREFIX: $PREFIX # false
      SESSION: $SESSION # true
