version: "3.9"
services:
  worker:
    build: .
    environment:
      BOT_TOKEN: $BOT_TOKEN # true
      API_ID: $API_ID  # true
      API_HASH: $API_HASH  # true
      MUSIC_BOT_NAME: $MUSIC_BOT_NAME  # true
      OWNER_ID: $OWNER_ID  # true
      STRING_SESSION1: $STRING_SESSION1 # true
